# Generated by Django 4.1.7 on 2023-02-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('Endereco', models.TextField(max_length=255)),
                ('Cidade', models.TextField(max_length=100)),
                ('Bairro', models.TextField(max_length=100)),
                ('CEP', models.TextField(max_length=8)),
                ('Fracao_ideal_tem', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('Estado', models.TextField(max_length=2)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='condominio_imagens')),
            ],
        ),
    ]
