# Generated by Django 4.1.7 on 2023-02-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_alter_condominio_bairro_alter_condominio_cep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloco',
            options={'verbose_name': 'Bloco', 'verbose_name_plural': 'Blocos'},
        ),
    ]
