# Generated by Django 4.1.7 on 2023-03-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_bloco_morador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='situacao',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
    ]
