# Generated by Django 4.1.7 on 2023-02-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='operacao',
            field=models.CharField(max_length=2),
        ),
    ]
