# Generated by Django 4.1.7 on 2023-02-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_contas_operacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='operacao',
        ),
        migrations.RemoveField(
            model_name='contas',
            name='situacao',
        ),
    ]
