# Generated by Django 4.1.7 on 2023-02-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_remove_contas_operacao_remove_contas_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='situacao',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
