# Generated by Django 4.1.7 on 2023-02-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_contas_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='operacao',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
