# Generated by Django 4.1.7 on 2023-02-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0002_morador_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='situacao',
            field=models.CharField(default='A', editable=False, max_length=1),
        ),
    ]
